<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Notification\Services;

class NotificationService extends \DTS\eBaySDK\Compliance\Services\NotificationBaseService
{
    const API_VERSION = 'v1';

    /**
     * @property array $operations Associative array of operations provided by the service.
     */
    protected static $operations = [
        'GetPublicKey' => [
		'method' => 'GET',
		'resource' => 'public_key/{public_key_id}',
		'responseClass' => '\DTS\eBaySDK\Taxonomy\Types\GetPublicKeyRestResponse',
		'params' => [
			'public_key_id' => [
				'valid' => ['string'],
				'required' => true
			]
		]
        ]
    ];

    /**
     * @param array $config Configuration option values.
     */
    public function __construct(array $config = [])
    {
        parent::__construct($config);
    }

    /**
     * @param \DTS\eBaySDK\Notification\Types\GetPublicKeyRestRequest $request
     * @return \DTS\eBaySDK\Notification\Types\GetPublicKeyRestResponse
     */
    public function getPublicKey(\DTS\eBaySDK\Notification\Types\GetPublicKeyRestRequest $request)
    {
        return $this->getPublicKeyAsync($request)->wait();
    }

    /**
     * @param \DTS\eBaySDK\Notification\Types\GetPublicKeyRestRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getPublicKeyAsync(\DTS\eBaySDK\Notification\Types\GetPublicKeyRestRequest $request)
    {
        return $this->callOperationAsync('GetPublicKey', $request);
    }
}
